'📒 Documentation':
  - changed-files:
    - any-glob-to-any-file:
        - '**/*.md'
        - '**/*.rst'
        - '**/*.asciidoc'
        - 'docs/**/*'
        - 'LICENSE'
        - 'CONTRIBUTING.md'
        - 'CHANGELOG.md'
        - 'README*'
        - 'CODE_OF_CONDUCT.md'
        - 'SECURITY.md'
  - head-branch:
    - '^(docs?|readme|typos?|comments?|document(ation)?)/i'

'🐛 Bug & Hotfix':
  - head-branch:
    - '^(fix|race|bug|missing|cor(rect)?|hotfix)/i'

'🧰 Maintenance & Updates':
  - head-branch:
    - '^(improve(ment)?|update|ref(actor)?|depr(ecated)?|rem(ove)?|clean(up)?|unus(ed)?|test(s)?|chore|enhance(ment)?)/i'

'📈 Performance':
  - head-branch:
    - '^(perf(ormance)?|optimize|optim(ization)?|bench(mark)?|speed(up)?)/i

'🤖 Dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'go.mod'
      - 'go.sum'
  - head-branch:
    - '^(deps?|bump|dependencies|update-deps?)/i'

'🚀 Features & Enhancements':
  - head-branch:
    - '^(feat(ure)?|create|impl(ement)?|add)/i'

'💥 Breaking-Change':
  - head-branch:
    - '^(break(ing)?|major)/i'

'🔒 Security':
  - head-branch:
    - '^(sec(urity)?|vul(nerability)?)/i'

'🏗️ CI/CD & Infrastructure':
  - changed-files:
    - any-glob-to-any-file: 
      - '.github/**/*'
      - '.circleci/**/*'
      - '.gitlab-ci.yml'
      - 'Jenkinsfile'
      - 'docker-compose.*'
      - 'compose.*'
      - 'Dockerfile'
      - 'Vagrantfile'
      - 'Makefile'
  - head-branch:
    - '^(ci|cd|docker(file)?|github|actions?)/i'

'⚙️ Configuration':
  - changed-files:
      - any-glob-to-any-file:
          - '.gitignore'
          - '.gitattributes'
          - '.env'
          - '.env.*'
  - head-branch:
      - '^(configs?|conf(iguration)?|settings?|setup)/i'