version: "v1"

labels:
  - label: 📒 Documentation
    matcher:
      branch: '(?i)^(docs?|readme|typos?|comments?|document(ation)?)/.*'
      files:
        - '**/*.md'
        - '**/*.rst'
        - '**/*.asciidoc'
        - 'docs/**/*'
        - 'LICENSE'
        - 'CONTRIBUTING.md'
        - 'CHANGELOG.md'
        - 'README*'
        - 'CODE_OF_CONDUCT.md'
        - 'SECURITY.md'

  - label: 🐛 Bug & Hotfix:
    matcher:
      branch: '(?i)^(fix|race|bug|missing|cor(rect)?|hotfix)/.*'

  - label: 🧰 Maintenance & Updates
    matcher:
      branch: '(?i)^(improve(ment)?|update|ref(actor)?|depr(ecated)?|rem(ove)?|clean(up)?|unus(ed)?|tests?|chore|enhance(ment)?)/.*'

  - label: 📈 Performance
    matcher:
      branch: '(?i)^(perf(ormance)?|optimize|optim(ization)?|bench(mark)?|speed(up)?)/.*'

  - label: 🤖 Dependencies
    matcher:
      branch: '(?i)^(deps?|bump|depend(encies)?|update-deps?)/.*'
      files:
        - 'go.mod'
        - 'go.sum'

  - label: 🚀 Features & Enhancements
    matcher:
      branch: '(?i)^(feat(ure)?|create|impl(ement)?|add)/.*'

  - label: 💥 Breaking-Change
    matcher:
      branch: '(?i)^(break(ing)?|major)/.*'

  - label: 🔒 Security
    matcher:
      branch: '(?i)^(sec(urity)?|vul(nerability)?)/.*'

  - label: 🏗️ CI/CD & Infrastructure
    matcher:
      branch: '(?i)^(ci|cd|docker(file)?|github|actions?)/.*'
      files:
        - '.github/**/*'
        - '.circleci/**/*'
        - '.gitlab-ci.yml'
        - 'Jenkinsfile'
        - 'docker-compose.*'
        - 'compose.*'
        - 'Dockerfile'
        - 'Vagrantfile'
        - 'Makefile'

  - label: ⚙️ Configuration
    matcher:
      branch: '(?i)^(configs?|conf(iguration)?|settings?|setup)/.*'
      files:
        - '.gitignore'
        - '.gitattributes'
        - '.env'
        - '.env.*'