📒 Documentation:
  files:
    - '**/*.md'
    - '**/*.rst'
    - '**/*.asciidoc'
    - 'docs/**/*'
    - 'LICENSE'
    - 'CONTRIBUTING.md'
    - 'CHANGELOG.md'
    - 'README*'
    - 'CODE_OF_CONDUCT.md'
    - 'SECURITY.md'
  branch:
    - '^docs?/.*'
    - '^readme/.*'
    - '^typos?/.*'
    - '^comments?/.*'
    - '^document(ation)?/.*'

🐛 Bug & Hotfix:
  branch:
    - '^fix/.*'
    - '^race/.*'
    - '^bug/.*'
    - '^missing/.*'
    - '^cor(rect)?/.*'
    - '^hotfix/.*'

🧰 Maintenance & Updates:
  branch:
    - '^improve(ment)?/.*'
    - '^update/.*'
    - '^ref(actor)?/.*'
    - '^depr(ecated)?/.*'
    - '^rem(ove)?/.*'
    - '^clean(up)?/.*'
    - '^unus(ed)?/.*'
    - '^test(s)?/.*'
    - '^chore/.*'
    - '^enhance(ment)?/.*'

📈 Performance:
  branch:
    - '^perf(ormance)?/.*'
    - '^optimize/.*'
    - '^optim(ization)?/.*'
    - '^bench(mark)?/.*'
    - '^speed(up)?/.*'

🤖 Dependencies:
  files:
    - 'go.mod'
    - 'go.sum'
  branch:
    - '^deps?/.*'
    - '^bump/.*'
    - '^depend(encies)?/.*'
    - '^update-deps?/.*'

🚀 Features & Enhancements:
  branch:
    - '^feat(ure)?/.*'
    - '^create/.*'
    - '^impl(ement)?/.*'
    - '^add/.*'

💥 Breaking-Change:
  branch:
    - '^break(ing)?/.*'
    - '^major/.*'

🔒 Security:
  branch:
    - '^sec(urity)?/.*'
    - '^vul(nerability)?/.*'

🏗️ CI/CD & Infrastructure:
  files:
    - '.github/**/*'
    - '.circleci/**/*'
    - '.gitlab-ci.yml'
    - 'Jenkinsfile'
    - 'docker-compose.*'
    - 'compose.*'
    - 'Dockerfile'
    - 'Vagrantfile'
    - 'Makefile'
  branch:
    - '^ci/.*'
    - '^cd/.*'
    - '^docker(file)?/.*'
    - '^github/.*'
    - '^actions?/.*'

⚙️ Configuration:
  files:
    - '.gitignore'
    - '.gitattributes'
    - '.env'
    - '.env.*'
  branch:
    - '^configs?/.*'
    - '^conf(iguration)?/.*'
    - '^settings?/.*'
    - '^setup/.*'