name: CI - Auto Labeler
on:
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4