name: CI - Release Drafter
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  release_drafter:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}